### PR TITLE
Vaas find cert paging, get vaas team/app by name

### PR DESCRIPTION
**Pull request by gdbarron**
- Add paging support to `Find-VenafiCertificate` for VaaS
- Update `Get-VaasApplication -ID` and `Get-VenafiTeam -ID` for VaaS to accept a name in addition to guid

### CODE REVIEW

**Comment by gdbarron** [comment]
@vertigo-one, can you please review the paging update?

**Comment by vertigo-one** [comment]
Great update to `Find-VenafiCertificate` VaaS functionality. 

**VaaS:** Testing confirms that '-first' acts as both a limit on the number of certificates returned and a page size if combined with 'includetotalcount' 

observed behavior
- `Find-VenafiCertificate -first 10` : returns first 10 certificates
- `Find-VenafiCertificate -first 5000` : returns 5000 certs, paging at the API limit of 1000 
- `Find-VenafiCertificate -first 50 -includetotalcount` : returns all certificates, paging at 50 per page
- `Find-VenafiCertificate -includetotalcount` : returns all certificates, paging at the api limit of 1000

the Verbose output does go negative for "Max left to retrieve", but this doesn't effect functionality. 

I did have some issues with piping `Find-VenafiCertificate` to `Get-VenafiCertificate` with the below error. I think this is the whole object from `Find-VenafiCertificate` being serialized into the URI that get-venaficertificate then calls, returning a 404

`PS C:\Users\vertigo-one> Find-VenafiCertificate -First 1 |Get-VenafiCertificate -Verbose
VERBOSE: Session is VenafiSession
VERBOSE:
{"ContentType":"application/json","Method":"Get","UseBasicParsing":true,"Headers":{"tppl-api-key":"***hidden***"},"Uri":"https://api.venafi.cloud/outagedetection/v1/certificates/@{id=0108dd50-a8c3-11ec-8cb3-2
bed8e5efbc8; companyId=1466c771-61f3-11ec-8a47-490a1e43c895; managedCertificateId=43503360-798a-11ec-8ed2-5b21d6b5f681; fingerprint=FB383DFAAE6392353FA32B0C975EAA5E9FD7AC2E;
issuerCertificateIds=System.Object[]; certificateStatus=ACTIVE; modificationDate=2022-03-21T03:00:03.143+00:00; archivedDate=2022-03-22T03:00:03.340+00:00; validityStart=2022-03-20T05:50:23.000+00:00;
validityEnd=2022-04-19T05:50:23.000+00:00; selfSigned=False; signatureAlgorithm=SHA256_WITH_RSA_ENCRYPTION; signatureHashAlgorithm=SHA256; encryptionType=RSA; keyStrength=2048;
subjectKeyIdentifierHash=209141286E2165300B4433142C315EA6366F4B7E; authorityKeyIdentifierHash=8521FA0F72EEAAA72F33ADCFE5704FC005F1CFA0; serialNumber=6C0001D0996F838BA72E8DD98F00000001D099; subjectDN=cn=<sanitized>; subjectCN=System.Object[]; subjectAlternativeNamesByType=; subjectAlternativeNameDns=System.Object[]; issuerDN=cn=Securafi Issuing
CA1,0.9.2342.19200300.100.1.25=net,0.9.2342.19200300.100.1.25=securafi,0.9.2342.19200300.100.1.25=lab; issuerCN=System.Object[]; keyUsage=System.Object[]; extendedKeyUsage=System.Object[]; ocspNoCheck=False;
versionType=OLD; totalInstanceCount=1; totalActiveInstanceCount=0; instances=System.Object[]; ownership=}"}
VERBOSE: Response status code 404
Invoke-WebRequest : The remote server returned an error: (404) Not Found.
At C:\Users\vertigo-one\Documents\Code_Projects\VenafiPS PR TESTING\VenafiPS\VenafiPS\Public\Invoke-VenafiRestMethod.ps1:224 char:40
+ ... put = $($response = Invoke-WebRequest @params -ErrorAction Stop) 4>&1
+                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand`

**Comment by gdbarron** [comment]
Thanks for the feedback @vertigo-one!  Pipelining fixed, was an issue with the object being converted to type string.  Removed max left message as I think it's just going to be confusing without knowing how many certs there are (the api doesn't expose that yet).

**Comment by vertigo-one** [comment]
Hey Greg. Looks good to me.

**Review by vertigo-one — APPROVED** [review]
Tested changes in paging functionality for VaaS. No issues.

**Pull request merged**
