### PR TITLE
Allow specifying a Timeout value

### LINKED ISSUE #237: Allow specifying a Timeout value
# Summary of the new feature/enhancement
Invoke-WebRequest and Invoke-RestMethod in PowerShell 5.1 have a default timeout of 0 (wait forever). Often times this behaviour is undesirable since this blocks program's execution. Venafi itself imposes a 120 seconds limit on Adaptable framework scripts, which is sometimes hit because Venafi PS was waiting on response from server while creating a new session. Often times this is due to temporary environmental factors such as badly configured load-balancers, network latency, load on server, etc. 

Since a developer can anticipate suitable timeout value for an environment they are developing for, ability to set timeout provides a much better way to handle such condition. For e.g. trying again for such (web) exceptions or handling the error differently and then exiting gracefully instead of endlessly waiting or having the entire program forcefully terminated. 

While it is possible to define a global timeout using ServicePointManager, this would effect every HTTP request made by the script, and not just the ones made by Venafi PS itself. 

# Proposed technical implementation details (optional)
Setting Timeout can be achieved by passing a value for timeout property of the underlaying Invoke-WebRequest method  with each call to Venafi PS function **and/or** allow setting a value for timeout when creating a new Venafi session object, which is used while establishing the session and subsequently by all functions when they invoke a call to Venafi’s API.

### PR DESCRIPTION
**Pull request by gdbarron**
closes #237

### CODE REVIEW

**Comment by Saadi6** [comment]
Thanks for the quick update. See my observations and comments below. 

**Without** wrapping New-VenafiSession in try catch statement and using 1 sec timeout resulted in an _incomplete_ VenafiSesison object. It was missing version and custom field definitions but token was present and useable. 

```
VERBOSE: {"Body":"{\"ConfigClass\":\"Application Base\"}","ContentType":"application/json","Method":"Post","TimeoutSec":1,"Headers":{"Authorization":"***hidden***"},"Uri":"https://tls.bigsur.local/vedsdk/Metadata/GetItemsForClass","UseBasicParsing":true}
VERBOSE: Response status code 0
PS /Users/saad.humayun> $VenafiSession                       

Platform             : VDC
AuthType             : Token
Expires              : 12/23/2023 4:23:14 PM
TimeoutSec           : 1
SkipCertificateCheck : False
Version              : 
CustomField          : 
Server               : https://tls.bigsur.local
Key                  : 
Token                : @{Server=https://tls.bigsur.local; AccessToken=System.Management.Automation.PSCredential; RefreshToken=; Scope=System.Collections.Hashtable; 
                       Identity=AD+BigSur:efd2ab3ac8f73a40ba4865ea5da1c035; TokenType=Bearer; ClientId=xxxxx; Expires=12/23/2023 4:23:14 PM; RefreshExpires=}
```

Wrapping New-VenafiSession in try catch statement returns an error upon first timeout.

```
VERBOSE: {"ContentType":"application/json","Method":"Get","TimeoutSec":1,"Headers":{"Authorization":"***hidden***"},"Uri":"https://tls.bigsur.local/vedsdk/SystemStatus/Version","UseBasicParsing":true}
VERBOSE: Response status code 0
Exception: untitled:Untitled-1:8:5
Line |
   8 |      throw $_.Exception.Message
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Getting the version failed with the following error: The request was canceled due to the configured HttpClient.Timeout of 1 seconds elapsing..  This
     | feature was introduced in v18.3.
```

A new session with a reasonable timeout specified has everything as expected. 

While this behaviour is as expected, it may confuse someone using a low timeout value without try catch, while using a function that happens to make several calls to Venafi API before a result is returned. 

I suggest throwing an error when _any_ call times out or adding a note in documentation that some errors due to low timeout value might be hidden if try and catch is not used.

**Review by Saadi6 — COMMENTED** [review]
**Without** wrapping New-VenafiSession in try catch statement and using 1 sec timeout resulted in an _incomplete_ VenafiSesison object. It was missing version and custom field definitions but token was present and useable. 

```
VERBOSE: {"Body":"{\"ConfigClass\":\"Application Base\"}","ContentType":"application/json","Method":"Post","TimeoutSec":1,"Headers":{"Authorization":"***hidden***"},"Uri":"https://tls.bigsur.local/vedsdk/Metadata/GetItemsForClass","UseBasicParsing":true}
VERBOSE: Response status code 0
PS /Users/saad.humayun> $VenafiSession                       

Platform             : VDC
AuthType             : Token
Expires              : 12/23/2023 4:23:14 PM
TimeoutSec           : 1
SkipCertificateCheck : False
Version              : 
CustomField          : 
Server               : https://tls.bigsur.local
Key                  : 
Token                : @{Server=https://tls.bigsur.local; AccessToken=System.Management.Automation.PSCredential; RefreshToken=; Scope=System.Collections.Hashtable; 
                       Identity=AD+BigSur:efd2ab3ac8f73a40ba4865ea5da1c035; TokenType=Bearer; ClientId=xxxxx; Expires=12/23/2023 4:23:14 PM; RefreshExpires=}
```

Wrapping New-VenafiSession in try catch statement returns an error upon first timeout.

```
VERBOSE: {"ContentType":"application/json","Method":"Get","TimeoutSec":1,"Headers":{"Authorization":"***hidden***"},"Uri":"https://tls.bigsur.local/vedsdk/SystemStatus/Version","UseBasicParsing":true}
VERBOSE: Response status code 0
Exception: untitled:Untitled-1:8:5
Line |
   8 |      throw $_.Exception.Message
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Getting the version failed with the following error: The request was canceled due to the configured HttpClient.Timeout of 1 seconds elapsing..  This
     | feature was introduced in v18.3.
```

A new session with a reasonable timeout specified has everything as expected. 

While this behaviour is as expected, it may confuse someone using a low timeout value without try catch, while using a function that happens to make several calls to Venafi API before a result is returned. 

I suggest throwing an error when _any_ call times out or adding a note in documentation that some errors due to low timeout value might be hidden if try and catch is not used.

**Comment by Saadi6** [comment]
comments submitted in review on GitHub

**Comment by gdbarron** [comment]
If someone uses a low timeout without error handling and an incomplete session is created, why doesn't the first call post New-VenafiSession fail?  I would think it would just as the calls to get version and CF info did.  Also, I would expect there to be errors for failure to retrieve version and CF, those are just not terminating errors so New-VenafiSession completes and does not stop the script.

Trying to understand the suggestion a bit deeper.  Is it to update Invoke-VenafiRestMethod to throw a **terminating** error whenever an api call fails, or just fails on timeout, or not terminating?  Or is the suggestion isolated to New-VenafiSession?  Or something else?

**Comment by gdbarron** [comment]
@Saadi6?

**Comment by Saadi6** [comment]
Excuse the late response. Without error handling while calling New-VenafiSession with a very short timeout value a terminating error does not occur, even though _some_ of the background HTTP calls made by VenafiPS (such as gathering custom fields) while creating the session object _did_ timeout. 

I am not sure why this is the case but wrapping New-VenafiSession in try catch statement - as one should - throws an error when any background HTTP request times out. 

Yes, if possible, Invoke-VenafiRestMethod can be updated to throw a terminating error only incase of timeout error. There might other implications if terminating error is thrown for all types of error by Invoke-VenafiRestMethod.

However, given that you don't know someone might use VenafiPS in their own code, just a warning/suggestion to always use error handling - when a timeout value is specified - would also be sufficient IMHO.

**Review by Saadi6 — APPROVED** [review]
Timeout feature works

**Pull request merged**
