### PR TITLE
Change ReadPolicy to FindPolicy and fix output

### PR DESCRIPTION
**Pull request by wilddev65**
Changes to using FindPolicy to get policy settings for an object and updates the output from various commands to only include custom field info when it is set and when there is a policy set to add the info as to where it is being set.

### CODE REVIEW

**Review by gdbarron — CHANGES_REQUESTED** [review]
when getting custom field attributes on a policy, `CustomFieldGuid` does not show up.

**Comment by gdbarron** [comment]
@wilddev65 that change looks good, but CustomFieldGuid still doesn't show unless the field has a value.  is this the behavior we want?

**Review by gdbarron — COMMENTED** [review]
that fixed worked, thanks.  CustomFieldGuid still doesn't show if a cf has no value.  is this the experience we want or should we show it either way?

**Comment by wilddev65** [comment]
The released version of the script had some issues with regards to both CustomFieldGuid and PolicyPath showing empty values on attributes where they would not ever be set on them. For example:
Last Renewed On: @{Value=09/16/2019 19:52:42; CustomFieldGuid=; Overridden=False; Locked=False; PolicyPath=}
I think it's confusing to have these attributes show when they have no value. The fix I added was just to not add them if they didn't have a value set. They will still have the custom field label in the output.
If someone needs the CustomFieldGuid, using Get-TppCustomField or simply looking it up in $VenafiSession should give them it.

**Review by gdbarron — CHANGES_REQUESTED** [review]
now the value is there, but not the key/value pair

**Comment by wilddev65** [comment]
Lol, cause I thought that was what you were asking for. Won't be hard to add 'customfield=' to it.

**Comment by gdbarron** [comment]
> Lol, cause I thought that was what you were asking for. Won't be hard to add 'customfield=' to it.

Ah, nope, want it to be consistent.

**Comment by wilddev65** [comment]
Okay, this should give you what you need. It just removes the 'Value' if it is blank from the output, so custom fields show both their guid and if they are locked.

**Review by gdbarron — APPROVED** [review]
looking good!

**Pull request merged**
